/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JIBIN JOSE
 */
public class addItem extends javax.swing.JFrame {

    /**
     * Creates new form addItem
     */
    public addItem() {
        initComponents();
        Stat_Up_Table();
    }
  String sqlk,a1,a2,a3,a4;
public void Stat_Up_Table()
{
        try {
            sqlk="select * from Category";
                          Class.forName("com.mysql.jdbc.Driver");
                           Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                             PreparedStatement pst=conn.prepareStatement(sqlk);
                            ResultSet rs=pst.executeQuery();
                              while(rs.next())
                            {
                                 a1=rs.getString(1);
                                 i3.addItem(a1);
                            }
         } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(addItem.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        i1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        i2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        i3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        i4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        i5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        i6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(695, 625));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addi.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(187, 61, 272, 52);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 179, 64, 24);

        i1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(i1);
        i1.setBounds(145, 177, 242, 31);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 243, 64, 22);

        i2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(i2);
        i2.setBounds(145, 236, 242, 29);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 304, 64, 15);

        i3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(i3);
        i3.setBounds(145, 296, 242, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 359, 36, 22);

        i4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(i4);
        i4.setBounds(145, 357, 242, 28);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stock");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 424, 51, 15);

        i5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(i5);
        i5.setBounds(145, 418, 242, 28);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Arrival Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 480, 70, 24);

        i6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        i6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                i6MouseEntered(evt);
            }
        });
        jPanel1.add(i6);
        i6.setBounds(145, 472, 242, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Addb.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(223, 530, 101, 46);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 60, 70, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adbg.PNG"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 700, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i6MouseEntered
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd ");
        Calendar cal = Calendar.getInstance();
        System.out.println(dateFormat.format(cal.getTime()));
        i6.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_i6MouseEntered

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        AdminHome admih=new AdminHome();
        admih.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseReleased
String t1,t2,t3,t4,t5,t6,inct;
    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        try {
            // TODO add your handling code here:
            t1=i1.getText();
            t2=i2.getText();
            t3=i3.getSelectedItem().toString();
            t4=i4.getText();
            t5=i5.getText();
            t6=i6.getText();
            inct="Insert into Additem values(?,?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
                 Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                 PreparedStatement pst=con.prepareStatement(inct);
                  pst.setString(1, t1);
                  pst.setString(2, t2);
                  pst.setString(3, t3);
                  pst.setString(4, t4);
                  pst.setString(5, t5);
                  pst.setString(6, t6);
                  if(!i2.getText().isEmpty()) {
                pst.execute();
                JOptionPane.showMessageDialog(this, "Successfully Added");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(addItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addItem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField i1;
    private javax.swing.JTextField i2;
    private javax.swing.JComboBox i3;
    private javax.swing.JTextField i4;
    private javax.swing.JTextField i5;
    private javax.swing.JTextField i6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
