/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.HomePanels.Overview;
import Frames.HomePanels.Reorder;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.Connection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JIBIN JOSE
 */
public class ClientInfo extends javax.swing.JFrame {
    DefaultTableModel deftm;
    /**
     * Creates new form ClientInfo
     */
    public ClientInfo() {
        initComponents();
        ClView();
        setSize(802, 749);
        jTextField5.setText("00001234");
    }
String yy1,yy2;
public void ClView()
{
    
        try {
            yy1="select * from Shop";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pst=conn.prepareStatement(yy1);
            ResultSet rs=pst.executeQuery();
                   while(rs.next())
                     {
                         yy2=rs.getString(1);
                         title.addItem(yy2);
                     }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        title = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        inwords = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        itno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itnam = new javax.swing.JLabel();
        ratt = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JLabel();
        indate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));
        setMinimumSize(new java.awt.Dimension(802, 749));
        setPreferredSize(new java.awt.Dimension(802, 749));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(805, 612));
        jPanel1.setPreferredSize(new java.awt.Dimension(805, 612));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Title of Shop");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 80, 25);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 190, 55, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 180, 210, 92);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Invoice Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 130, 73, 25);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 180, 59, 23);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      Bill No.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 240, 70, 24);

        jTextField5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(590, 240, 151, 30);

        title.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        title.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                titleItemStateChanged(evt);
            }
        });
        jPanel1.add(title);
        title.setBounds(150, 120, 210, 30);

        Table.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Particulars", "Quantity", "Rate", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setMinWidth(60);
            Table.getColumnModel().getColumn(0).setPreferredWidth(80);
            Table.getColumnModel().getColumn(0).setMaxWidth(100);
            Table.getColumnModel().getColumn(1).setMinWidth(240);
            Table.getColumnModel().getColumn(1).setPreferredWidth(260);
            Table.getColumnModel().getColumn(1).setMaxWidth(280);
            Table.getColumnModel().getColumn(2).setMinWidth(120);
            Table.getColumnModel().getColumn(2).setPreferredWidth(140);
            Table.getColumnModel().getColumn(2).setMaxWidth(160);
            Table.getColumnModel().getColumn(3).setMinWidth(120);
            Table.getColumnModel().getColumn(3).setPreferredWidth(140);
            Table.getColumnModel().getColumn(3).setMaxWidth(160);
            Table.getColumnModel().getColumn(4).setMinWidth(140);
            Table.getColumnModel().getColumn(4).setPreferredWidth(160);
            Table.getColumnModel().getColumn(4).setMaxWidth(180);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(45, 420, 700, 145);

        inwords.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(inwords);
        inwords.setBounds(10, 570, 309, 24);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Amount   :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 580, 93, 23);

        total.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(total);
        total.setBounds(610, 580, 90, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill invoice.PNG"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 30, 214, 45);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Item No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 310, 50, 15);

        itno.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itnoKeyReleased(evt);
            }
        });
        jPanel1.add(itno);
        itno.setBounds(150, 300, 210, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 370, 60, 15);

        quantity.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(quantity);
        quantity.setBounds(150, 360, 210, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Item Name");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 310, 60, 15);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rate ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(540, 370, 30, 15);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(27, 22, 70, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cadd.PNG"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 330, 70, 40);

        itnam.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itnam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(itnam);
        itnam.setBounds(590, 304, 150, 30);

        ratt.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ratt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ratt);
        ratt.setBounds(590, 360, 140, 30);

        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(590, 180, 150, 20);

        indate.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        indate.setForeground(new java.awt.Color(255, 255, 255));
        indate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                indateMouseEntered(evt);
            }
        });
        jPanel1.add(indate);
        indate.setBounds(590, 130, 150, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoicebg.PNG"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 620);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 805, 612);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(805, 130));
        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jCheckBox1.setText("Print after Save");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(30, 60, 123, 25);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cprint.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel17);
        jLabel17.setBounds(370, 40, 101, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/csaveb.png"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(795, 300));
        jLabel16.setMinimumSize(new java.awt.Dimension(795, 300));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel16MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel16);
        jLabel16.setBounds(500, 40, 110, 42);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccancelB.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel15MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(640, 40, 102, 42);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ibgn.PNG"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(0, 0, 965, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 618, 805, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        // TODO add your handling code here:
        try{
            deftm=(DefaultTableModel) Table.getModel();
            int rct=Table.getRowCount();
            if(rct>0){
                JOptionPane.showMessageDialog(null, "You should clear the Rows!");
            }
            else if(rct==0){
            try{
                uj1=Table.getValueAt(Table.getSelectedRow(), 1).toString();
                //uj2=Table.getValueAt(Table.getSelectedRow(), 1).toString();
                uj3=Table.getValueAt(Table.getSelectedRow(), 2).toString();
                uj4=ratt.getText();
                addfc1=Table.getValueAt(Table.getSelectedRow(), 4).toString();
                ej3=Integer.parseInt(addfc1);
                ej4=Integer.parseInt(total.getText());
            }catch(Exception e){

            }
            sjj="select Stock from additem where Itemname=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pstp=conn1.prepareStatement(sjj);
            pstp.setString(1, uj1);
            ResultSet rsg=pstp.executeQuery();
            while(rsg.next())
            {
                lkk=rsg.getString("Stock");
                ej1=Integer.parseInt(lkk);
                ej2=Integer.parseInt(uj3);
                sdf="Update additem set Stock=? where Itemname=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection connn1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                PreparedStatement st1=connn1.prepareStatement(sdf);
                add=ej1+ej2;
                subfc=ej4-ej3;
                String famt=String.valueOf(subfc);
                st1.setString(1 , ""+add);
                st1.setString(2, uj1);
                c=st1.executeUpdate();
                if(c>0){
                    total.setText(famt);
                    //JOptionPane.showMessageDialog(null, add);
                }
            }
            try{
                deftm.removeRow(Table.getSelectedRow());
            }catch(Exception e){
            }
        AdminHome aohme=new AdminHome();
        aohme.setVisible(true);
        this.setVisible(false);
     }
            }catch(ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e){
            //JOptionPane.showMessageDialog(null, "we are Unable to Process!");
        };
    }//GEN-LAST:event_jLabel14MouseReleased
String sey,ghj;
    private void itnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itnoKeyReleased
        try {
            // TODO add your handling code here:
            ghj=itno.getText();
            sey="Select * from additem where Itemno='"+ghj+"'";
            Class.forName("com.mysql.jdbc.Driver");
                      Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                        PreparedStatement pst=conn.prepareStatement(sey);
                       ResultSet rs=pst.executeQuery();
                       //pst.setString(1, itna.getText());
                       if(rs.next()){
                           String val0=rs.getString("Itemname");
                           itnam.setText(val0);
                           String val1=rs.getString("Stock");
                           quantity.setText(val1);
                           String val2=rs.getString("Price");
                           ratt.setText(val2);
                       }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itnoKeyReleased
String ur5,p6,p7,p8,p9,iamount;
int find1,find2,calculate,j,sum;
String p10;
    public void Populate(String isrn,String iname,String iquant,String irate,String iamount)
{
    deftm=(DefaultTableModel) Table.getModel();
    try{
    String[] rowData={isrn,iname,iquant,irate,iamount};
    deftm.addRow(rowData);
    }catch(Exception e){
    }
}
    String ur1,ur2,ur3,ur4,lk6,lk7,lk8,lk9,slq,cal ;
    int j1,j2,grandtotal=0,e1,e2,f;
    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        try {
            ur1=itnam.getText();
            ur2=itno.getText();
            ur3=quantity.getText();
            ur4=ratt.getText();
           slq="select Stock from additem where Itemname=?";
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
         PreparedStatement pstp=conn.prepareStatement(slq);
         pstp.setString(1, ur1);
         ResultSet rs=pstp.executeQuery();
               while(rs.next())
                   {                
                       lk6=rs.getString("Stock");
                       e1=Integer.parseInt(lk6);
                       e2=Integer.parseInt(ur3);
                       if(e2<=e1 && !itno.getText().isEmpty())
                       {
                             find1=(int) Float.parseFloat(ur3);
                             find2=(int) Float.parseFloat(ur4);
                             calculate=find1*find2;
                             grandtotal=grandtotal+calculate;
                             total.setText(String.valueOf(grandtotal));
                             cal=String.valueOf(calculate);
                             String sqh="Update additem set Stock=? where Itemname=?";
                         Class.forName("com.mysql.jdbc.Driver");
                         Connection connn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                         PreparedStatement pststmm=connn.prepareStatement(sqh);
                         int sub=e1-e2;
                         pststmm.setString(1 , ""+sub);
                         pststmm.setString(2, ur1);
                         p=pststmm.executeUpdate();
                         if(p>0){
                             JOptionPane.showMessageDialog(null, sub);
                         }
                            Populate(ur2, ur1, ur3, ur4, cal);
                       }
                       else
                       {
                           JOptionPane.showMessageDialog(null, "Error!\n Enter the Correct value!");
                       }
                   }
           
            itnam.setText("");
            itno.setText("");
            quantity.setText("");
            ratt.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseReleased
String value,qval;
    private void titleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_titleItemStateChanged
        try {
            // TODO add your handling code here:
            value=title.getSelectedItem().toString();
                qval="Select * from Shop where Title='"+value+"'";
                Class.forName("com.mysql.jdbc.Driver");
                          Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                            PreparedStatement pst=conn.prepareStatement(qval);
                           ResultSet rs=pst.executeQuery();
                           //pst.setString(1, itna.getText());
                           if(rs.next()){
                               String val10=rs.getString("Address");
                               jTextArea1.setText(val10);
                               String val11=rs.getString("Username");
                               jTextField3.setText(val11);
                             }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_titleItemStateChanged

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
        // TODO add your handling code here:
        try{
            deftm=(DefaultTableModel) Table.getModel();
            int rct=Table.getRowCount();
            try{
                uj1=Table.getValueAt(Table.getSelectedRow(), 1).toString();
                //uj2=Table.getValueAt(Table.getSelectedRow(), 1).toString();
                uj3=Table.getValueAt(Table.getSelectedRow(), 2).toString();
                uj4=ratt.getText();
                addfc1=Table.getValueAt(Table.getSelectedRow(), 4).toString();
                ej3=Integer.parseInt(addfc1);
                ej4=Integer.parseInt(total.getText());
            }catch(Exception e){

            }
            sjj="select Stock from additem where Itemname=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pstp=conn1.prepareStatement(sjj);
            pstp.setString(1, uj1);
            ResultSet rsg=pstp.executeQuery();
            while(rsg.next())
            {
                lkk=rsg.getString("Stock");
                ej1=Integer.parseInt(lkk);
                ej2=Integer.parseInt(uj3);
                sdf="Update additem set Stock=? where Itemname=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection connn1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                PreparedStatement st1=connn1.prepareStatement(sdf);
                add=ej1+ej2;
                st1.setString(1 , ""+add);
                st1.setString(2, uj1);
                subfc=ej4-ej3;
                String famt=String.valueOf(subfc);
                c=st1.executeUpdate();
                if(c>0){
                    total.setText(famt);
                    //JOptionPane.showMessageDialog(null, add);
                }
            }
            try{
                deftm.removeRow(Table.getSelectedRow());
            }catch(Exception e){
            }

        }catch(ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e){
            //JOptionPane.showMessageDialog(null, "we are Unable to Process!");
        };
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jLabel16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseReleased
        try {
            // TODO add your handling code here:

            w1=title.getSelectedItem().toString();
            w2="Your Request has to be Processed!";
            w3=jTextArea1.getText();
            w4=indate.getText();
            w5=jTextField3.getText();
            w6=jTextField5.getText();
            w7=total.getText();
            try{
                Overview.ldpcs.setText(w4);
            }catch(Exception e){

            }
            mcount=Table.getRowCount();
            sqwery="Insert into Showprintbil values(?,?,?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pststm=con.prepareStatement(sqwery);
            pststm.setString(1, w1);
            pststm.setString(2, w2);
            pststm.setString(3, w3);
            pststm.setString(4, w4);
            pststm.setString(5, w5);
            pststm.setString(6, w6);
            pststm.setString(7, w7);
            if(!title.getSelectedItem().toString().isEmpty()) {
                pststm.execute();
                JOptionPane.showMessageDialog(null, "Saved!");
                AdminHome ainh=new AdminHome();
                ainh.setVisible(true);
                if(jCheckBox1.isSelected()){
           PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("ClientInfo");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum){
                if(pageNum>0)
                {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2=(Graphics2D) pg;
                g2=Translator(pf.getImageableX(),pf.getImageableY());
                jPanel1.paint(g2);
                return Printable.PAGE_EXISTS;

            }
            private Graphics2D Translator(double imageableX, double imageableY) {
                throw new UnsupportedOperationException("Not yet implemented");
            }
        });
        boolean ok=job.printDialog();
        if(ok)
        {
            try
            {
                job.print();
            }catch(PrinterException ex){}
        }
 
        }
                this.setVisible(false);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel16MouseReleased

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("ClientInfo");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum){
                if(pageNum>0)
                {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2=(Graphics2D) pg;
                g2=Translator(pf.getImageableX(),pf.getImageableY());
                jPanel1.paint(g2);
                return Printable.PAGE_EXISTS;

            }
            private Graphics2D Translator(double imageableX, double imageableY) {
                throw new UnsupportedOperationException("Not yet implemented");
            }
        });
        boolean ok=job.printDialog();
        if(ok)
        {
            try
            {
                job.print();
            }catch(PrinterException ex){}
        }

    }//GEN-LAST:event_jLabel17MouseReleased
public static String jgetdate;
    private void indateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indateMouseEntered
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd  ");
        Calendar cal = Calendar.getInstance();
        System.out.println(dateFormat.format(cal.getTime()));
        indate.setText(dateFormat.format(cal.getTime()));
        try{
            jgetdate=indate.getText();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_indateMouseEntered

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed
int add,ej1,ej2,c,ej3,ej4,subfc;
String uj1,uj2,uj3,uj4,sjj,lkk,sdf,addfc1;
String w1,w2,w3,w4,w5,w6,w7,w8,sqwery,carry,carryt,getitnam;
int mcount,i,jk,jkj,ert,p;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel indate;
    private javax.swing.JLabel inwords;
    private javax.swing.JLabel itnam;
    private javax.swing.JTextField itno;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel ratt;
    public static javax.swing.JComboBox title;
    public static javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
