/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JIBIN JOSE
 */
public class Edit extends javax.swing.JFrame {
DefaultTableModel dml;
    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        Up_tab();
        Edit_Up();
    }
String squeryy,stated;
    public void Edit_Up()
    {
        try {
            squeryy="select * from Category";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pst=conn.prepareStatement(squeryy);
            ResultSet rs=pst.executeQuery();
                   while(rs.next())
                     {
                        stated=rs.getString(1);
                        m3.addItem(stated);
                     }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    String bj1,bj2,bj3,bj4,bj5,bj6;
public void Up_tab(){
        try {              
            dml=(DefaultTableModel)edittable.getModel();
               while(edittable.getRowCount()>0)
                {
                    for(int i=0;i<edittable.getRowCount();i++)
                    {
                        dml.removeRow(0);
                        //JOptionPane.showMessageDialog(null, i);
                    }
                }
                 String sql="select * from additem";
                 Class.forName("com.mysql.jdbc.Driver");
                  Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                    PreparedStatement pst=conn.prepareStatement(sql);
                   ResultSet rs=pst.executeQuery();
                     while(rs.next())
                   {
                        bj1=rs.getString(1);
                        bj2=rs.getString(2);
                        bj3=rs.getString(3);
                        bj4=rs.getString(4);
                        bj5=rs.getString(5);
                        bj6=rs.getString(6);
                       Object raw[]={bj1,bj2,bj3,bj4,bj5,bj6};
                       dml.addRow(raw);
                  }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
}
 private void filte(String str)
 {
     TableRowSorter<DefaultTableModel> tr2=new TableRowSorter<DefaultTableModel> (dml);
     edittable.setRowSorter(tr2);
    tr2.setRowFilter(RowFilter.regexFilter(str));
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        m5 = new javax.swing.JTextField();
        updbtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edittable = new javax.swing.JTable();
        jsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m6 = new javax.swing.JTextField();
        m3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(811, 560));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editi.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 40, 402, 61);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item No. ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 180, 56, 25);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 240, 80, 25);

        m1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m1);
        m1.setBounds(180, 180, 220, 30);

        m2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m2);
        m2.setBounds(180, 240, 220, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 430, 60, 26);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arrival Date ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 490, 80, 25);

        m4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m4);
        m4.setBounds(180, 370, 218, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rate");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 370, 70, 30);

        m5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m5);
        m5.setBounds(180, 430, 218, 30);

        updbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UPDBTN.png"))); // NOI18N
        updbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updbtnMouseReleased(evt);
            }
        });
        jPanel1.add(updbtn);
        updbtn.setBounds(210, 560, 143, 45);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 40, 70, 70);

        edittable.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        edittable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Category", "Price", "Stock", "Arrival Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        edittable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edittableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(edittable);
        edittable.getColumnModel().getColumn(0).setMinWidth(40);
        edittable.getColumnModel().getColumn(0).setPreferredWidth(80);
        edittable.getColumnModel().getColumn(0).setMaxWidth(80);
        edittable.getColumnModel().getColumn(1).setMinWidth(120);
        edittable.getColumnModel().getColumn(1).setPreferredWidth(180);
        edittable.getColumnModel().getColumn(1).setMaxWidth(200);
        edittable.getColumnModel().getColumn(2).setMinWidth(90);
        edittable.getColumnModel().getColumn(2).setPreferredWidth(120);
        edittable.getColumnModel().getColumn(2).setMaxWidth(120);
        edittable.getColumnModel().getColumn(3).setMinWidth(80);
        edittable.getColumnModel().getColumn(3).setPreferredWidth(100);
        edittable.getColumnModel().getColumn(3).setMaxWidth(120);
        edittable.getColumnModel().getColumn(4).setMinWidth(80);
        edittable.getColumnModel().getColumn(4).setPreferredWidth(130);
        edittable.getColumnModel().getColumn(4).setMaxWidth(130);
        edittable.getColumnModel().getColumn(5).setMinWidth(120);
        edittable.getColumnModel().getColumn(5).setPreferredWidth(130);
        edittable.getColumnModel().getColumn(5).setMaxWidth(140);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(600, 170, 670, 270);

        jsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jsearch);
        jsearch.setBounds(1010, 80, 230, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textfield_searchwidget_selected.9.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(960, 70, 40, 50);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Category");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 300, 80, 30);

        m6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m6);
        m6.setBounds(180, 490, 220, 30);

        m3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(m3);
        m3.setBounds(180, 310, 220, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edbcgd.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1900, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        AdminHome adh=new AdminHome();
        adh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyReleased
        // TODO add your handling code here:
         String str1=jsearch.getText().toLowerCase();
        filte(str1);
    }//GEN-LAST:event_jsearchKeyReleased
String j1,j2,j3,j4,j5,j6;
    private void edittableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittableMouseClicked
        // TODO add your handling code here:
        j1=edittable.getValueAt(edittable.getSelectedRow(), 0).toString();
        j2=edittable.getValueAt(edittable.getSelectedRow(), 1).toString();
        //j3=edittable.getValueAt(edittable.getSelectedRow(), 2).toString();
        j4=edittable.getValueAt(edittable.getSelectedRow(), 3).toString();
        j5=edittable.getValueAt(edittable.getSelectedRow(), 4).toString();
        j6=edittable.getValueAt(edittable.getSelectedRow(), 5).toString();
        m1.setText(j1);
        m2.setText(j2);
        //m3.addItem(j3);
        m4.setText(j4);
        m5.setText(j5);
        m6.setText(j6);
    }//GEN-LAST:event_edittableMouseClicked
String n1,n2,n3,n4,n5,n6,n7,sql1;
int i;
    private void updbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updbtnMouseReleased
        try {
            // TODO add your handling code here:
            n1=m1.getText();
            n2=m2.getText();
            n3=m3.getSelectedItem().toString();
            n4=m4.getText();
            n5=m5.getText();
            n6=m6.getText();
            sql1="Update additem set Itemno=?,Itemname=?,Category=?,Price=?,Stock=?,Arrivaldate=? where Itemno='"+n1+"'";
             Class.forName("com.mysql.jdbc.Driver");
              Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                     PreparedStatement pst=con.prepareStatement(sql1);
                      pst.setString(1, n1);
                      pst.setString(2, n2);
                      pst.setString(3, n3);
                      pst.setString(4, n4);
                      pst.setString(5, n5);
                      pst.setString(6, n6);
                      i=pst.executeUpdate();
                      if(!n2.isEmpty()) {
                    if(i>0){
                    JOptionPane.showMessageDialog(this, "Updated Successfully!");
                }
                 }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updbtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable edittable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jsearch;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JComboBox m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JLabel updbtn;
    // End of variables declaration//GEN-END:variables
}
