/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JIBIN JOSE
 */
public final class Inbox extends javax.swing.JFrame {
DefaultTableModel dtm;
    /**
     * Creates new form Inbox
     */
    public Inbox() {
        initComponents();
        Update_tablee();
        int cou=inbtable.getRowCount();
        String w=String.valueOf(cou);
        countm.setText(w);
    }
String e1,e2,e3,sqe;
public void Update_tablee(){
        try {        
            dtm=(DefaultTableModel)inbtable.getModel();
               while(inbtable.getRowCount()>0)
                {
                    for(int i=0;i<inbtable.getRowCount();i++)
                    {
                        dtm.removeRow(0);
                        //JOptionPane.showMessageDialog(null, i);
                    }
                }
                 sqe="select * from Inboxtab";
                 Class.forName("com.mysql.jdbc.Driver");
                  Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                    PreparedStatement pst=conn.prepareStatement(sqe);
                   ResultSet rs=pst.executeQuery();
                     while(rs.next())
                   {
                        e1=rs.getString(1);
                        e2=rs.getString(2);
                        e3=rs.getString(3);
                        Object raw[]={e1,e2,e3};
                       dtm.addRow(raw);
                    }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Inbox.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inbtable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        countm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(715, 481));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/in.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(258, 67, 182, 51);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anyshare_invite_icon_email.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 380, 72, 72);

        inbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Message", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inbtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inbtable);
        inbtable.getColumnModel().getColumn(0).setMinWidth(120);
        inbtable.getColumnModel().getColumn(0).setPreferredWidth(180);
        inbtable.getColumnModel().getColumn(0).setMaxWidth(200);
        inbtable.getColumnModel().getColumn(2).setMinWidth(80);
        inbtable.getColumnModel().getColumn(2).setPreferredWidth(90);
        inbtable.getColumnModel().getColumn(2).setMaxWidth(100);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 171, 695, 178);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Messages : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(540, 134, 80, 20);

        countm.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        countm.setForeground(new java.awt.Color(0, 51, 102));
        countm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                countmMouseEntered(evt);
            }
        });
        jPanel1.add(countm);
        countm.setBounds(620, 130, 50, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 70, 70, 50);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Show");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 424, 120, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INBG.PNG"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-1, -16, 850, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        // TODO add your handling code here:
        AdminHome anhme=new AdminHome();
        anhme.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        dtm=(DefaultTableModel) inbtable.getModel();
        r=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 0);
        j=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 1);
        l=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 2);
        InboxView ibvw=new InboxView();
        ibvw.setVisible(true);
         try{
              InboxView.shpnm.setText(r);
              InboxView.lotim.setText(j);
              InboxView.dopse.setText(l);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Couldn't do this!");
         } 
    }//GEN-LAST:event_jLabel2MouseReleased
String sqj,je1,je2,j,r,l;
    private void inbtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inbtableMouseClicked
        // TODO add your handling code here:
        dtm=(DefaultTableModel) inbtable.getModel();
        r=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 0);
        j=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 1);
        l=(String) inbtable.getValueAt(inbtable.getSelectedRow(), 2);
        if(evt.getClickCount()==2){
         InboxView ibvw=new InboxView();
         ibvw.setVisible(true);
         try{
              InboxView.shpnm.setText(r);
              InboxView.lotim.setText(j);
              InboxView.dopse.setText(l);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Couldn't do this!");
         }
         }
    }//GEN-LAST:event_inbtableMouseClicked

    private void countmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countmMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_countmMouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel7.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel7.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel7.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inbox().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countm;
    public static javax.swing.JTable inbtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
