/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JIBIN JOSE
 */
public class NewAccount extends javax.swing.JFrame {

    /**
     * Creates new form NewAccount
     */
    public NewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tshop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nown = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        doj = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        unam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        captchaval = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New User Account");
        setMinimumSize(new java.awt.Dimension(630, 760));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cna.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 40, 345, 43);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Title of Shop ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(38, 118, 100, 27);
        jPanel1.add(tshop);
        tshop.setBounds(160, 120, 251, 27);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("Name of Owner");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(38, 164, 87, 25);
        jPanel1.add(nown);
        nown.setBounds(160, 170, 251, 25);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("Address ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(38, 208, 53, 25);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 210, 251, 96);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("City ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(38, 336, 35, 15);
        jPanel1.add(city);
        city.setBounds(160, 330, 251, 28);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("Phone ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(38, 379, 43, 23);
        jPanel1.add(phone);
        phone.setBounds(160, 380, 251, 29);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("Email ID ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(38, 430, 51, 15);
        jPanel1.add(email);
        email.setBounds(160, 420, 251, 29);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 0));
        jLabel8.setText("Date of Join ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(38, 471, 73, 25);
        jPanel1.add(doj);
        doj.setBounds(160, 470, 251, 25);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 0));
        jLabel9.setText("UserName ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(38, 515, 62, 24);
        jPanel1.add(unam);
        unam.setBounds(160, 510, 251, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 570, 62, 15);
        jPanel1.add(pass1);
        pass1.setBounds(160, 560, 251, 28);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("Re-type Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 620, 100, 15);
        jPanel1.add(pass2);
        pass2.setBounds(160, 610, 252, 28);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(176, 664, 134, 45);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Enter the Captcha");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(451, 440, 115, 15);
        jPanel1.add(captchaval);
        captchaval.setBounds(451, 464, 115, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/captcha.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(451, 377, 127, 45);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgnac.PNG"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, -70, 630, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String h1,h2,h3,h4,hg;
    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        try {
            // TODO add your handling code here:
            h1=String.valueOf(pass1.getPassword());
            h2=String.valueOf(pass2.getPassword());
            hg="Insert into Shop values(?,?,?,?,?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
                 Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                 PreparedStatement pstt=con.prepareStatement(hg);
                  pstt.setString(1, tshop.getText());
                  pstt.setString(2, nown.getText());
                  pstt.setString(3, ta.getText());
                  pstt.setString(4, city.getText());
                  pstt.setString(5, phone.getText());
                  pstt.setString(6, email.getText());
                  pstt.setString(7, doj.getText());
                  pstt.setString(8, unam.getText());
                   pstt.setString(9, h2);
                  if(!tshop.getText().isEmpty()) {
                      if(h1.equals(h2)&&(captchaval.getText().equals("jKP87n"))){
                        pstt.execute();
                        JOptionPane.showMessageDialog(null, "Successfully Added");
                       }
                      else if(!h1.equals(h2)){
                          JOptionPane.showMessageDialog(null, "Passwords are does not Match!");
                      }
                      else if(!captchaval.getText().equals("jKP87n")){
                          JOptionPane.showMessageDialog(null, "Captcha Validation is Unsuccessful!");
                      }
                      }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel12MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captchaval;
    private javax.swing.JTextField city;
    private javax.swing.JTextField doj;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nown;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField phone;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tshop;
    private javax.swing.JTextField unam;
    // End of variables declaration//GEN-END:variables
}
