/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JIBIN JOSE
 */
public class RemoveShop extends javax.swing.JFrame {

    /**
     * Creates new form RemoveShop
     */
    public RemoveShop() {
        initComponents();
        Del_Shopusr();
    }
String gt1,gt2;
public void Del_Shopusr()
 {
        try {
            gt1="select * from Shop";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pst=conn.prepareStatement(gt1);
            ResultSet rs=pst.executeQuery();
                  while(rs.next())
                     {
                         gt2=rs.getString(1);
                         t1.addItem(gt2);
                     }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RemoveShop.class.getName()).log(Level.SEVERE, null, ex);
        }
            
 }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datetim = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(701, 598));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rmshop.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 50, 290, 45);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title of Shop ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(57, 168, 87, 28);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Owner of the Shop");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(57, 232, 110, 15);

        t2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(171, 226, 231, 28);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(57, 294, 48, 23);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(171, 294, 231, 81);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UserName ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(57, 420, 64, 26);

        t3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(t3);
        t3.setBounds(171, 420, 231, 29);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Note:This may delete every");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 240, 182, 15);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("details of the Shop.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 260, 182, 15);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/removeb.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(196, 497, 136, 46);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(557, 392, 0, 0);

        datetim.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        datetim.setForeground(new java.awt.Color(255, 255, 255));
        datetim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datetimMouseEntered(evt);
            }
        });
        jPanel1.add(datetim);
        datetim.setBounds(530, 20, 150, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 50, 70, 40);

        t1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        t1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                t1ItemStateChanged(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(170, 160, 230, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rmbg.PNG"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-3, -6, 1230, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datetimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datetimMouseEntered
        // TODO add your handling code here:
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd ");
        Calendar cal = Calendar.getInstance();
        System.out.println(dateFormat.format(cal.getTime()));
        datetim.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_datetimMouseEntered

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        AdminHome amh=new AdminHome();
        amh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        RshopDelConfirm rdc=new RshopDelConfirm();
        rdc.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseReleased
String val20,squeryyy;
    private void t1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_t1ItemStateChanged
        try {
            // TODO add your handling code here:
            val20=t1.getSelectedItem().toString();
                    squeryyy="Select * from Shop where Title='"+val20+"'";
                    Class.forName("com.mysql.jdbc.Driver");
                              Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                                PreparedStatement pst=conn.prepareStatement(squeryyy);
                               ResultSet rs=pst.executeQuery();
                               //pst.setString(1, itna.getText());
                               if(rs.next()){
                                   String val14=rs.getString("Owner");
                                   t2.setText(val14);
                                   String val15=rs.getString("Address");
                                   ta1.setText(val15);
                                   String val16=rs.getString("Username");
                                   t3.setText(val16);
                                 }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RemoveShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveShop().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datetim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox t1;
    public static javax.swing.JTextField t2;
    public static javax.swing.JTextField t3;
    public static javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
