/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JIBIN JOSE
 */
public class removeItem extends javax.swing.JFrame {

    /**
     * Creates new form removeItem
     */
    public removeItem() {
        initComponents();
        Rem_Cat();
    }
String sqlqy,getits;
public void Rem_Cat()
{
        try {
            sqlqy="select * from Category";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
            PreparedStatement pst=conn.prepareStatement(sqlqy);
            ResultSet rs=pst.executeQuery();
              while(rs.next())
                  {
                     getits=rs.getString(1);
                     r3.addItem(getits);
                  }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(removeItem.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        r3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        r8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 518));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rmitem.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 60, 311, 52);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Item No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(72, 164, 60, 24);

        r1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        r1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                r1KeyReleased(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(160, 160, 230, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(72, 224, 60, 22);

        r2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(r2);
        r2.setBounds(160, 220, 230, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("Category ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 280, 60, 25);

        r3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(r3);
        r3.setBounds(160, 280, 230, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/removebu.PNG"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 370, 155, 44);

        r8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        r8.setForeground(new java.awt.Color(0, 0, 255));
        r8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                r8MouseEntered(evt);
            }
        });
        jPanel1.add(r8);
        r8.setBounds(603, 26, 112, 23);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Note:This will delete the complete ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 200, 260, 15);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("details of the Item.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(460, 220, 160, 15);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn_tap02.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 60, 70, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ritembg.PNG"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 730, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r8MouseEntered
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd ");
        Calendar cal = Calendar.getInstance();
        System.out.println(dateFormat.format(cal.getTime()));
        r8.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_r8MouseEntered

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
        AdminHome aom=new AdminHome();
        aom.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
        DelConfirm dcfm=new DelConfirm();
        dcfm.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseReleased
String getiten;
    private void r1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r1KeyReleased
        try {
            // TODO add your handling code here:
            getiten=r1.getText();
            String sqlitnm="select * from additem where Itemno='"+getiten+"'";
                         Class.forName("com.mysql.jdbc.Driver");
                          Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                            PreparedStatement pst=conn.prepareStatement(sqlitnm);
                           ResultSet rs=pst.executeQuery();
                             while(rs.next())
                           {
                                String val55=rs.getString("Itemname");
                                r2.setText(val55);
                           }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(removeItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeItem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField r1;
    public static javax.swing.JTextField r2;
    public static javax.swing.JComboBox r3;
    private javax.swing.JLabel r8;
    // End of variables declaration//GEN-END:variables
}
