/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author JIBIN JOSE
 */
public class ShowBillPrint extends javax.swing.JFrame {

    /**
     * Creates new form ShowBillPrint
     */
    public ShowBillPrint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlb1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlb2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(785, 685));
        setPreferredSize(new java.awt.Dimension(785, 685));
        getContentPane().setLayout(null);

        jpa.setBackground(new java.awt.Color(255, 255, 255));
        jpa.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Title of Shop :");
        jpa.add(jLabel1);
        jLabel1.setBounds(40, 170, 89, 24);

        jlb1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jlb1);
        jlb1.setBounds(130, 170, 240, 27);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("BILL RECEIPT/ SLIP");
        jpa.add(jLabel3);
        jLabel3.setBounds(270, 70, 240, 38);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Location  :");
        jpa.add(jLabel4);
        jLabel4.setBounds(59, 220, 61, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jLabel5);
        jLabel5.setBounds(130, 170, 176, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Invoice Date :");
        jpa.add(jLabel6);
        jLabel6.setBounds(500, 180, 90, 19);

        jlb4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jlb4);
        jlb4.setBounds(580, 170, 123, 40);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText(" Username :");
        jpa.add(jLabel8);
        jLabel8.setBounds(510, 230, 70, 15);

        jlb5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jlb5);
        jlb5.setBounds(580, 220, 150, 40);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("    Bill No:");
        jpa.add(jLabel10);
        jLabel10.setBounds(60, 350, 60, 20);

        jlb3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jlb3);
        jlb3.setBounds(130, 350, 196, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wserfd.jpg"))); // NOI18N
        jpa.add(jLabel12);
        jLabel12.setBounds(680, 420, 80, 76);

        jlb2.setColumns(20);
        jlb2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlb2.setRows(5);
        jScrollPane1.setViewportView(jlb2);

        jpa.add(jScrollPane1);
        jScrollPane1.setBounds(130, 230, 200, 81);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setText("Total Amount :");
        jpa.add(jLabel13);
        jLabel13.setBounds(490, 280, 90, 20);

        jlb6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jpa.add(jlb6);
        jlb6.setBounds(580, 270, 120, 40);

        jlb8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jpa.add(jlb8);
        jlb8.setBounds(150, 484, 210, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yourbill.jpg"))); // NOI18N
        jpa.add(jLabel9);
        jLabel9.setBounds(10, 10, 200, 117);

        getContentPane().add(jpa);
        jpa.setBounds(0, 0, 776, 505);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printb.PNG"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(330, 80, 122, 49);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jLabel7.setText("the Order will be Cancelled! And also,you must have the Amount as Specified above. ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 40, 530, 30);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jLabel2.setText("* You should come at the Office within 3 Days with this Bill Slip to take the Ordered items.Otherwise,");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 20, 630, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 511, 776, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        // TODO add your handling code here:
        PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("Bill Slip");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum){
                if(pageNum>0)
                {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2=(Graphics2D) pg;
                g2=Translator(pf.getImageableX(),pf.getImageableY());
                jpa.paint(g2);
                return Printable.PAGE_EXISTS;
               
            }
            private Graphics2D Translator(double imageableX, double imageableY) {
                throw new UnsupportedOperationException("Not yet implemented");
            }
        });
        boolean ok=job.printDialog();
        if(ok)
        {
            try
            {
                job.print();
            }catch(PrinterException ex){}
        }        
    }//GEN-LAST:event_jLabel11MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowBillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowBillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowBillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowBillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowBillPrint().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel jlb1;
    public static javax.swing.JTextArea jlb2;
    public static javax.swing.JLabel jlb3;
    public static javax.swing.JLabel jlb4;
    public static javax.swing.JLabel jlb5;
    public static javax.swing.JLabel jlb6;
    public static javax.swing.JLabel jlb8;
    private javax.swing.JPanel jpa;
    // End of variables declaration//GEN-END:variables
}
