/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.HomePanels;

import Frames.AdminHome;
import Frames.BillPayHome;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JIBIN JOSE
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        adur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adpwd = new javax.swing.JPasswordField();
        afyu = new javax.swing.JLabel();
        incp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1181, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1181, 300));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("UserName :");
        add(jLabel2);
        jLabel2.setBounds(67, 158, 64, 34);

        adur.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        add(adur);
        adur.setBounds(141, 159, 232, 34);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Password  :");
        add(jLabel3);
        jLabel3.setBounds(67, 214, 64, 25);

        adpwd.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        add(adpwd);
        adpwd.setBounds(141, 211, 232, 33);

        afyu.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        afyu.setForeground(new java.awt.Color(255, 0, 102));
        add(afyu);
        afyu.setBounds(80, 260, 242, 28);

        incp.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        incp.setForeground(new java.awt.Color(255, 0, 102));
        add(incp);
        incp.setBounds(330, 260, 198, 28);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adm.PNG"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(479, 59, 213, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(404, 181, 102, 35);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("Note:");
        add(jLabel7);
        jLabel7.setBounds(737, 121, 35, 15);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Administrator has the Complete Power of this system.");
        add(jLabel8);
        jLabel8.setBounds(782, 119, 374, 17);

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("The Admin can Add,Remove Items and Shops to or from Database. ");
        add(jLabel9);
        jLabel9.setBounds(737, 142, 434, 15);

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("And also, Edit,Search in items and the power of bill invoice. ");
        add(jLabel11);
        jLabel11.setBounds(737, 163, 434, 15);

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("So,the Unauthorized Access is restricted!");
        add(jLabel12);
        jLabel12.setBounds(737, 184, 291, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/billing-services.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(40, 40, 240, 95);
    }// </editor-fold>//GEN-END:initComponents
String usrn,pass,strr,us1,pw1,u1,u2;
    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        try {
            // TODO add your handling code here:
             usrn=adur.getText();
             pass=String.valueOf(adpwd.getPassword());
            strr="select * from Admin where Username=? and Password=?";
            Class.forName("com.mysql.jdbc.Driver");
       Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
        PreparedStatement sts=con.prepareStatement(strr);
        sts.setString(1, usrn);
        sts.setString(2, pass);
        ResultSet rs=sts.executeQuery();
        while(rs.next()){
                us1=rs.getString("Username");
                pw1=rs.getString("Password");
                if(us1.equals(usrn) && pw1.equals(pass)){
                    AdminHome aihm=new AdminHome();
                    aihm.setVisible(true);
                    this.setVisible(false);
                }
                else if(usrn.equals("") || !usrn.equals(us1)){
                     afyu.setText("Are you Forgot your UserName?");
                }
                else if(pass.equals("") || !pass.equals(pw1)){
                      incp.setText("Incorrect Password!");
                }
                 else{
                    JOptionPane.showMessageDialog(null, "We are Unable to Process!");
                 }
 
            }   
          } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adpwd;
    private javax.swing.JTextField adur;
    private javax.swing.JLabel afyu;
    private javax.swing.JLabel incp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
