/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.HomePanels;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JIBIN JOSE
 */
public class ChangePasswd extends javax.swing.JPanel {

    /**
     * Creates new form ChangePasswd
     */
    public ChangePasswd() {
        initComponents();
        setSize(697, 447);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        oldpwd1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        npwd2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        npwd3 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 229, 66));
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(697, 369));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(697, 369));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Current Password");
        add(jLabel1);
        jLabel1.setBounds(130, 120, 120, 30);
        add(oldpwd1);
        oldpwd1.setBounds(270, 120, 240, 30);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("New Password");
        add(jLabel2);
        jLabel2.setBounds(130, 180, 110, 50);
        add(npwd2);
        npwd2.setBounds(270, 190, 240, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Confirm Password ");
        add(jLabel3);
        jLabel3.setBounds(130, 260, 120, 30);
        add(npwd3);
        npwd3.setBounds(270, 260, 240, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chpwdbg.PNG"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(140, 10, 364, 64);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/changebtn.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        add(jLabel5);
        jLabel5.setBounds(270, 320, 140, 46);
    }// </editor-fold>//GEN-END:initComponents
String op,np,np1,squ;
int g;
    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        try {
            // TODO add your handling code here:
            op=String.valueOf(oldpwd1.getPassword());
            np=String.valueOf(npwd2.getPassword());
            np1=String.valueOf(npwd3.getPassword());
            squ="Update Admin set Password='"+np+"'where Password='"+op+"'";
             Class.forName("com.mysql.jdbc.Driver");
                  Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                         PreparedStatement pst=con.prepareStatement(squ);
                         g=pst.executeUpdate();
                          if(!String.valueOf(npwd3).isEmpty()) {
                        if(g>0){
                        JOptionPane.showMessageDialog(this, "Password Changed!");
                    }
                     }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ChangePasswd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField npwd2;
    private javax.swing.JPasswordField npwd3;
    private javax.swing.JPasswordField oldpwd1;
    // End of variables declaration//GEN-END:variables
}
