/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.HomePanels;

import Frames.BillPayHome;
import Frames.NewAccount;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JIBIN JOSE
 */
public class Homee extends javax.swing.JPanel {
    /**
     * Creates new form Homee
     */
    public Homee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usrt1 = new javax.swing.JTextField();
        pwdp1 = new javax.swing.JPasswordField();
        invaliduser = new javax.swing.JLabel();
        wrongpasswd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1181, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1181, 300));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(10, 40, 120, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("UserName ");
        add(jLabel2);
        jLabel2.setBounds(40, 110, 71, 23);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(40, 160, 63, 24);

        usrt1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        add(usrt1);
        usrt1.setBounds(107, 104, 170, 30);

        pwdp1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        add(pwdp1);
        pwdp1.setBounds(105, 156, 170, 30);

        invaliduser.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        invaliduser.setForeground(new java.awt.Color(255, 0, 0));
        add(invaliduser);
        invaliduser.setBounds(317, 100, 151, 28);

        wrongpasswd.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        wrongpasswd.setForeground(new java.awt.Color(255, 0, 51));
        add(wrongpasswd);
        wrongpasswd.setBounds(317, 151, 151, 30);

        jLabel6.setFont(new java.awt.Font("DFKai-SB", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 204));
        jLabel6.setText("Login as Administrator");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(970, 50, 207, 15);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bigstock.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(590, 40, 300, 220);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lgu.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        add(jLabel8);
        jLabel8.setBounds(210, 220, 102, 30);

        jLabel9.setFont(new java.awt.Font("Constantia", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Create new Account");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        add(jLabel9);
        jLabel9.setBounds(990, 230, 160, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
          BillPayHome.adm.setVisible(true);
          BillPayHome.hm.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        // TODO add your handling code here:
        NewAccount nwa=new NewAccount();
        nwa.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseReleased
String s1,s2,swq,s3,s4;
    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        try {
            // TODO add your handling code here:
            s1=usrt1.getText();
            s2=String.valueOf(pwdp1.getPassword());
            swq="Select Username,Password from Shop where Username='"+s1+"' and Password='"+s2+"'";
            Class.forName("com.mysql.jdbc.Driver");
                      Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                        PreparedStatement pst=conn.prepareStatement(swq);
                       ResultSet rs=pst.executeQuery();
                         while(rs.next())
                       {
                            s3=rs.getString("Username");
                            s4=rs.getString("Password");
                            if(s3.equals(s1) && s4.equals(s2)){
                                BillPayHome.nr.setVisible(true);
                                BillPayHome.hm.setVisible(false);
                            }
                            else if(s1.equals("") || !s1.equals(s3)){
                                invaliduser.setText("Invalid Username!");
                                //invaliduser.setText("");
                            }
                            else if(s2.equals("") || !s2.equals(s4)){
                               wrongpasswd.setText("Wrong Password!");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "We are Unable to Process!");
                            }
                       }
                         
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Homee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invaliduser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPasswordField pwdp1;
    public javax.swing.JTextField usrt1;
    private javax.swing.JLabel wrongpasswd;
    // End of variables declaration//GEN-END:variables
}
