/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.HomePanels;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JIBIN JOSE
 */
public final class ItemView extends javax.swing.JPanel {
DefaultTableModel model;
    /**
     * Creates new form ItemView
     */
    public ItemView() {
        initComponents();
         Update_table(); 
    }
    String itc1,itc2,itc3,itc4,itc5,itc6;
    public void Update_table(){
        try {
            model=(DefaultTableModel)vitemtable.getModel();
               while(vitemtable.getRowCount()>0)
                {
                    for(int i=0;i<vitemtable.getRowCount();i++)
                    {
                        model.removeRow(0);
                        //JOptionPane.showMessageDialog(null, i);
                    }
                }
                 String sql="select * from additem";
                 Class.forName("com.mysql.jdbc.Driver");
                  Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                    PreparedStatement pst=conn.prepareStatement(sql);
                   ResultSet rs=pst.executeQuery();
                     while(rs.next())
                   {
                        itc1=rs.getString(1);
                        itc2=rs.getString(2);
                        itc3=rs.getString(3);
                         itc4=rs.getString(4);
                        itc5=rs.getString(5);
                         itc6=rs.getString(6);
                       Object raw[]={itc1,itc2,itc3,itc4,itc5,itc6};
                       model.addRow(raw);
                       int lo=Integer.parseInt(itc5);
                       if(lo<50)
                       {
                           try{
                               String itc7=rs.getString("Itemname");
                           Reorder.rcombo.addItem(itc7);
                           String itc8=rs.getString("Stock");
                           Reorder.rit2.setText(itc8);
                           }catch(Exception e){
                               
                           }
                       }
                  }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void filter(String query)
{
    TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel> (model);
    vitemtable.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitemtable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        filtertxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(923, 589));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(923, 589));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VITEMS.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Item No. :");

        h1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Item Name  :");

        h2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Category  :");

        h3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h3.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Price  :");

        h4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h4.setForeground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Stock  :");

        h5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h5.setForeground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Arrival Date  :");

        h6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        h6.setForeground(new java.awt.Color(0, 102, 102));

        vitemtable.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        vitemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Category", "Price", "Stock", "Arrival Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vitemtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vitemtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vitemtable);
        vitemtable.getColumnModel().getColumn(0).setMinWidth(30);
        vitemtable.getColumnModel().getColumn(0).setPreferredWidth(60);
        vitemtable.getColumnModel().getColumn(0).setMaxWidth(60);
        vitemtable.getColumnModel().getColumn(1).setMinWidth(100);
        vitemtable.getColumnModel().getColumn(1).setPreferredWidth(120);
        vitemtable.getColumnModel().getColumn(1).setMaxWidth(120);
        vitemtable.getColumnModel().getColumn(2).setMinWidth(90);
        vitemtable.getColumnModel().getColumn(2).setPreferredWidth(100);
        vitemtable.getColumnModel().getColumn(2).setMaxWidth(110);
        vitemtable.getColumnModel().getColumn(3).setMinWidth(80);
        vitemtable.getColumnModel().getColumn(3).setPreferredWidth(80);
        vitemtable.getColumnModel().getColumn(3).setMaxWidth(90);
        vitemtable.getColumnModel().getColumn(4).setMinWidth(90);
        vitemtable.getColumnModel().getColumn(4).setPreferredWidth(90);
        vitemtable.getColumnModel().getColumn(4).setMaxWidth(100);
        vitemtable.getColumnModel().getColumn(5).setMinWidth(90);
        vitemtable.getColumnModel().getColumn(5).setPreferredWidth(90);
        vitemtable.getColumnModel().getColumn(5).setMaxWidth(110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textfield_searchwidget_selected.9.png"))); // NOI18N

        filtertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtertxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(filtertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtertxtKeyReleased
        // TODO add your handling code here:
        String query=filtertxt.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_filtertxtKeyReleased
String uy1,uy2,uy3,uy4,uy5,uy6;
    private void vitemtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vitemtableMouseClicked
        // TODO add your handling code here:
        uy1=vitemtable.getValueAt(vitemtable.getSelectedRow(), 0).toString();
        uy2=vitemtable.getValueAt(vitemtable.getSelectedRow(), 1).toString();
        uy3=vitemtable.getValueAt(vitemtable.getSelectedRow(), 2).toString();
        uy4=vitemtable.getValueAt(vitemtable.getSelectedRow(), 3).toString();
        uy5=vitemtable.getValueAt(vitemtable.getSelectedRow(), 4).toString();
        uy6=vitemtable.getValueAt(vitemtable.getSelectedRow(), 5).toString();
        h1.setText(uy1);
        h2.setText(uy2);
        h3.setText(uy3);
        h4.setText(uy4);
        h5.setText(uy5);
        h6.setText(uy6);
    }//GEN-LAST:event_vitemtableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filtertxt;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable vitemtable;
    // End of variables declaration//GEN-END:variables
}
