/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.HomePanels;

import Frames.BillPayHome;
import Frames.EditProfile;
import Frames.Inbox;
import Frames.InboxView;
import Frames.LookupChart;
import com.mysql.jdbc.Connection;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.TextEvent;
import java.awt.event.TextListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JIBIN JOSE
 */
public class NewReg extends javax.swing.JPanel {
    /**
     * Creates new form NewReg
     */
    public NewReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        ustm = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1181, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1181, 300));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rq.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(21, 20, 248, 41);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Shop Name :");
        add(jLabel2);
        jLabel2.setBounds(21, 109, 85, 18);

        sn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        sn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snKeyReleased(evt);
            }
        });
        add(sn);
        sn.setBounds(110, 104, 167, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Address      :");
        add(jLabel3);
        jLabel3.setBounds(21, 165, 80, 18);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(111, 165, 206, 81);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("List of Items :");
        add(jLabel4);
        jLabel4.setBounds(365, 109, 103, 18);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2);
        jScrollPane2.setBounds(472, 104, 213, 108);

        ustm.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ustm.setForeground(new java.awt.Color(153, 0, 153));
        ustm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ustmMouseEntered(evt);
            }
        });
        add(ustm);
        ustm.setBounds(1030, 20, 140, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/re.PNG"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(768, 129, 130, 34);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signout.PNG"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        add(jLabel7);
        jLabel7.setBounds(1040, 240, 110, 41);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Edit Your Profile");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        add(jLabel8);
        jLabel8.setBounds(1030, 60, 140, 20);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        add(jLabel5);
        jLabel5.setBounds(790, 190, 160, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("*You should specify the unit/quantity for each Item as per the Lookup Chart");
        add(jLabel9);
        jLabel9.setBounds(380, 270, 440, 15);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lookup.PNG"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        add(jLabel10);
        jLabel10.setBounds(470, 10, 240, 50);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Item No.");
        add(jLabel11);
        jLabel11.setBounds(480, 80, 60, 15);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Quantity");
        add(jLabel12);
        jLabel12.setBounds(630, 80, 60, 15);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("-");
        add(jLabel13);
        jLabel13.setBounds(570, 80, 40, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        // TODO add your handling code here:
       BillPayHome.hm.setVisible(true);
       BillPayHome.nr.setVisible(false);
       BillPayHome.adm.setVisible(false);
       BillPayHome.cs.setVisible(false);
       BillPayHome.hm.usrt1.setText("");
       BillPayHome.hm.pwdp1.setText("");
    }//GEN-LAST:event_jLabel7MouseReleased

    private void ustmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ustmMouseEntered
        // TODO add your handling code here:\
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd  ");
        Calendar cal = Calendar.getInstance();
        System.out.println(dateFormat.format(cal.getTime()));
        ustm.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_ustmMouseEntered

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        EditProfile edpfle=new EditProfile();
        edpfle.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseReleased
String adssr,nb1,yui;
String spname,lsmts,dtget;
    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        try {
            // TODO add your handling code here:
            //dtm=(DefaultTableModel) Inbox.inbtable.getModel();
            spname=sn.getText();
            lsmts=jTextArea2.getText();
            dtget=ustm.getText();
            String sql="Insert into Inboxtab values(?,?,?)";
                  Class.forName("com.mysql.jdbc.Driver");
                 Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                 PreparedStatement pstst=con.prepareStatement(sql);
                 pstst.setString(1, spname);
                  pstst.setString(2, lsmts);
                  pstst.setString(3, dtget);
                  if(!jTextArea2.getText().isEmpty()) {
                    pstst.execute();
                    jLabel5.setText("Requesting.");
                    jLabel5.setText("Requesting..");
                    jLabel5.setText("Requesting...");
                    jLabel5.setText("Requested");
                    JOptionPane.showMessageDialog(this, "Requested!");
                    }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseReleased

    private void snKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snKeyReleased
      
            // TODO add your handling code here:
            try{
            adssr=sn.getText();
            String sql="select * from Shop where Title='"+adssr+"'";
                     Class.forName("com.mysql.jdbc.Driver");
                      Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/pbs","root","koha123");
                        PreparedStatement pst=conn.prepareStatement(sql);
                       ResultSet rs=pst.executeQuery();
                         while(rs.next())
                       {
                            String val5=rs.getString("Address");
                            jTextArea1.setText(val5);
                       }
                         
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_snKeyReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        LookupChart lkch=new LookupChart();
        lkch.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextField sn;
    private javax.swing.JLabel ustm;
    // End of variables declaration//GEN-END:variables
}
